//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;
using DoddleAudit.EntityFramework;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("ECommerceModel", "Product_Category", "Categories", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(DoddleAudit.Tests.EFObjectContext.Category), "Products", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(DoddleAudit.Tests.EFObjectContext.Product), true)]
[assembly: EdmRelationshipAttribute("ECommerceModel", "Product_Promotions", "Products", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(DoddleAudit.Tests.EFObjectContext.Product), "Promotions", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(DoddleAudit.Tests.EFObjectContext.Promotion), true)]
[assembly: EdmRelationshipAttribute("ECommerceModel", "AuditRecordProperty_AuditRecord", "AuditRecord", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(DoddleAudit.Tests.EFObjectContext.AuditRecord), "AuditRecordProperty", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(DoddleAudit.Tests.EFObjectContext.AuditRecordProperty), true)]

#endregion

namespace DoddleAudit.Tests.EFObjectContext
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class ECommerceEntities : AuditableObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new ECommerceEntities object using the connection string found in the 'ECommerceEntities' section of the application configuration file.
        /// </summary>
        public ECommerceEntities() : base("name=ECommerceEntities", "ECommerceEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new ECommerceEntities object.
        /// </summary>
        public ECommerceEntities(string connectionString) : base(connectionString, "ECommerceEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new ECommerceEntities object.
        /// </summary>
        public ECommerceEntities(EntityConnection connection) : base(connection, "ECommerceEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Category> Categories
        {
            get
            {
                if ((_Categories == null))
                {
                    _Categories = base.CreateObjectSet<Category>("Categories");
                }
                return _Categories;
            }
        }
        private ObjectSet<Category> _Categories;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Product> Products
        {
            get
            {
                if ((_Products == null))
                {
                    _Products = base.CreateObjectSet<Product>("Products");
                }
                return _Products;
            }
        }
        private ObjectSet<Product> _Products;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Promotion> Promotions
        {
            get
            {
                if ((_Promotions == null))
                {
                    _Promotions = base.CreateObjectSet<Promotion>("Promotions");
                }
                return _Promotions;
            }
        }
        private ObjectSet<Promotion> _Promotions;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<AuditRecordProperty> AuditRecordProperties
        {
            get
            {
                if ((_AuditRecordProperties == null))
                {
                    _AuditRecordProperties = base.CreateObjectSet<AuditRecordProperty>("AuditRecordProperties");
                }
                return _AuditRecordProperties;
            }
        }
        private ObjectSet<AuditRecordProperty> _AuditRecordProperties;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<AuditRecord> AuditRecords
        {
            get
            {
                if ((_AuditRecords == null))
                {
                    _AuditRecords = base.CreateObjectSet<AuditRecord>("AuditRecords");
                }
                return _AuditRecords;
            }
        }
        private ObjectSet<AuditRecord> _AuditRecords;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Categories EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCategories(Category category)
        {
            base.AddObject("Categories", category);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Products EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToProducts(Product product)
        {
            base.AddObject("Products", product);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Promotions EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToPromotions(Promotion promotion)
        {
            base.AddObject("Promotions", promotion);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the AuditRecordProperties EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToAuditRecordProperties(AuditRecordProperty auditRecordProperty)
        {
            base.AddObject("AuditRecordProperties", auditRecordProperty);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the AuditRecords EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToAuditRecords(AuditRecord auditRecord)
        {
            base.AddObject("AuditRecords", auditRecord);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ECommerceModel", Name="AuditRecord")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class AuditRecord : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new AuditRecord object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="action">Initial value of the Action property.</param>
        /// <param name="auditDate">Initial value of the AuditDate property.</param>
        /// <param name="parentKey">Initial value of the ParentKey property.</param>
        /// <param name="tableKey">Initial value of the TableKey property.</param>
        public static AuditRecord CreateAuditRecord(global::System.Int32 id, global::System.Byte action, global::System.DateTime auditDate, global::System.Int32 parentKey, global::System.Int32 tableKey)
        {
            AuditRecord auditRecord = new AuditRecord();
            auditRecord.Id = id;
            auditRecord.Action = action;
            auditRecord.AuditDate = auditDate;
            auditRecord.ParentKey = parentKey;
            auditRecord.TableKey = tableKey;
            return auditRecord;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte Action
        {
            get
            {
                return _Action;
            }
            set
            {
                OnActionChanging(value);
                ReportPropertyChanging("Action");
                _Action = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Action");
                OnActionChanged();
            }
        }
        private global::System.Byte _Action;
        partial void OnActionChanging(global::System.Byte value);
        partial void OnActionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime AuditDate
        {
            get
            {
                return _AuditDate;
            }
            set
            {
                OnAuditDateChanging(value);
                ReportPropertyChanging("AuditDate");
                _AuditDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("AuditDate");
                OnAuditDateChanged();
            }
        }
        private global::System.DateTime _AuditDate;
        partial void OnAuditDateChanging(global::System.DateTime value);
        partial void OnAuditDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ParentTable
        {
            get
            {
                return _ParentTable;
            }
            set
            {
                OnParentTableChanging(value);
                ReportPropertyChanging("ParentTable");
                _ParentTable = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ParentTable");
                OnParentTableChanged();
            }
        }
        private global::System.String _ParentTable;
        partial void OnParentTableChanging(global::System.String value);
        partial void OnParentTableChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ParentKey
        {
            get
            {
                return _ParentKey;
            }
            set
            {
                OnParentKeyChanging(value);
                ReportPropertyChanging("ParentKey");
                _ParentKey = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ParentKey");
                OnParentKeyChanged();
            }
        }
        private global::System.Int32 _ParentKey;
        partial void OnParentKeyChanging(global::System.Int32 value);
        partial void OnParentKeyChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Table
        {
            get
            {
                return _Table;
            }
            set
            {
                OnTableChanging(value);
                ReportPropertyChanging("Table");
                _Table = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Table");
                OnTableChanged();
            }
        }
        private global::System.String _Table;
        partial void OnTableChanging(global::System.String value);
        partial void OnTableChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 TableKey
        {
            get
            {
                return _TableKey;
            }
            set
            {
                OnTableKeyChanging(value);
                ReportPropertyChanging("TableKey");
                _TableKey = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TableKey");
                OnTableKeyChanged();
            }
        }
        private global::System.Int32 _TableKey;
        partial void OnTableKeyChanging(global::System.Int32 value);
        partial void OnTableKeyChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String UserName
        {
            get
            {
                return _UserName;
            }
            set
            {
                OnUserNameChanging(value);
                ReportPropertyChanging("UserName");
                _UserName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("UserName");
                OnUserNameChanged();
            }
        }
        private global::System.String _UserName;
        partial void OnUserNameChanging(global::System.String value);
        partial void OnUserNameChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ECommerceModel", "AuditRecordProperty_AuditRecord", "AuditRecordProperty")]
        public EntityCollection<AuditRecordProperty> AuditRecordProperties
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<AuditRecordProperty>("ECommerceModel.AuditRecordProperty_AuditRecord", "AuditRecordProperty");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<AuditRecordProperty>("ECommerceModel.AuditRecordProperty_AuditRecord", "AuditRecordProperty", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ECommerceModel", Name="AuditRecordProperty")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class AuditRecordProperty : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new AuditRecordProperty object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="auditRecordId">Initial value of the AuditRecordId property.</param>
        public static AuditRecordProperty CreateAuditRecordProperty(global::System.Int32 id, global::System.Int32 auditRecordId)
        {
            AuditRecordProperty auditRecordProperty = new AuditRecordProperty();
            auditRecordProperty.Id = id;
            auditRecordProperty.AuditRecordId = auditRecordId;
            return auditRecordProperty;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 AuditRecordId
        {
            get
            {
                return _AuditRecordId;
            }
            set
            {
                OnAuditRecordIdChanging(value);
                ReportPropertyChanging("AuditRecordId");
                _AuditRecordId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("AuditRecordId");
                OnAuditRecordIdChanged();
            }
        }
        private global::System.Int32 _AuditRecordId;
        partial void OnAuditRecordIdChanging(global::System.Int32 value);
        partial void OnAuditRecordIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PropertyName
        {
            get
            {
                return _PropertyName;
            }
            set
            {
                OnPropertyNameChanging(value);
                ReportPropertyChanging("PropertyName");
                _PropertyName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PropertyName");
                OnPropertyNameChanged();
            }
        }
        private global::System.String _PropertyName;
        partial void OnPropertyNameChanging(global::System.String value);
        partial void OnPropertyNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String OldValue
        {
            get
            {
                return _OldValue;
            }
            set
            {
                OnOldValueChanging(value);
                ReportPropertyChanging("OldValue");
                _OldValue = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("OldValue");
                OnOldValueChanged();
            }
        }
        private global::System.String _OldValue;
        partial void OnOldValueChanging(global::System.String value);
        partial void OnOldValueChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String NewValue
        {
            get
            {
                return _NewValue;
            }
            set
            {
                OnNewValueChanging(value);
                ReportPropertyChanging("NewValue");
                _NewValue = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("NewValue");
                OnNewValueChanged();
            }
        }
        private global::System.String _NewValue;
        partial void OnNewValueChanging(global::System.String value);
        partial void OnNewValueChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ECommerceModel", "AuditRecordProperty_AuditRecord", "AuditRecord")]
        public AuditRecord AuditRecord
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<AuditRecord>("ECommerceModel.AuditRecordProperty_AuditRecord", "AuditRecord").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<AuditRecord>("ECommerceModel.AuditRecordProperty_AuditRecord", "AuditRecord").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<AuditRecord> AuditRecordReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<AuditRecord>("ECommerceModel.AuditRecordProperty_AuditRecord", "AuditRecord");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<AuditRecord>("ECommerceModel.AuditRecordProperty_AuditRecord", "AuditRecord", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ECommerceModel", Name="Category")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Category : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Category object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        public static Category CreateCategory(global::System.Int32 id)
        {
            Category category = new Category();
            category.Id = id;
            return category;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CategoryName
        {
            get
            {
                return _CategoryName;
            }
            set
            {
                OnCategoryNameChanging(value);
                ReportPropertyChanging("CategoryName");
                _CategoryName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CategoryName");
                OnCategoryNameChanged();
            }
        }
        private global::System.String _CategoryName;
        partial void OnCategoryNameChanging(global::System.String value);
        partial void OnCategoryNameChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ECommerceModel", "Product_Category", "Products")]
        public EntityCollection<Product> Products
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Product>("ECommerceModel.Product_Category", "Products");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Product>("ECommerceModel.Product_Category", "Products", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ECommerceModel", Name="Product")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Product : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Product object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="categoryId">Initial value of the CategoryId property.</param>
        public static Product CreateProduct(global::System.Int32 id, global::System.Int32 categoryId)
        {
            Product product = new Product();
            product.Id = id;
            product.CategoryId = categoryId;
            return product;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ProductName
        {
            get
            {
                return _ProductName;
            }
            set
            {
                OnProductNameChanging(value);
                ReportPropertyChanging("ProductName");
                _ProductName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ProductName");
                OnProductNameChanged();
            }
        }
        private global::System.String _ProductName;
        partial void OnProductNameChanging(global::System.String value);
        partial void OnProductNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 CategoryId
        {
            get
            {
                return _CategoryId;
            }
            set
            {
                OnCategoryIdChanging(value);
                ReportPropertyChanging("CategoryId");
                _CategoryId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CategoryId");
                OnCategoryIdChanged();
            }
        }
        private global::System.Int32 _CategoryId;
        partial void OnCategoryIdChanging(global::System.Int32 value);
        partial void OnCategoryIdChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ECommerceModel", "Product_Category", "Categories")]
        public Category Category
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Category>("ECommerceModel.Product_Category", "Categories").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Category>("ECommerceModel.Product_Category", "Categories").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Category> CategoryReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Category>("ECommerceModel.Product_Category", "Categories");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Category>("ECommerceModel.Product_Category", "Categories", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ECommerceModel", "Product_Promotions", "Promotions")]
        public EntityCollection<Promotion> Promotions
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Promotion>("ECommerceModel.Product_Promotions", "Promotions");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Promotion>("ECommerceModel.Product_Promotions", "Promotions", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ECommerceModel", Name="Promotion")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Promotion : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Promotion object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="discountAmount">Initial value of the DiscountAmount property.</param>
        /// <param name="productId">Initial value of the ProductId property.</param>
        public static Promotion CreatePromotion(global::System.Int32 id, global::System.Decimal discountAmount, global::System.Int32 productId)
        {
            Promotion promotion = new Promotion();
            promotion.Id = id;
            promotion.DiscountAmount = discountAmount;
            promotion.ProductId = productId;
            return promotion;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal DiscountAmount
        {
            get
            {
                return _DiscountAmount;
            }
            set
            {
                OnDiscountAmountChanging(value);
                ReportPropertyChanging("DiscountAmount");
                _DiscountAmount = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DiscountAmount");
                OnDiscountAmountChanged();
            }
        }
        private global::System.Decimal _DiscountAmount;
        partial void OnDiscountAmountChanging(global::System.Decimal value);
        partial void OnDiscountAmountChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ProductId
        {
            get
            {
                return _ProductId;
            }
            set
            {
                OnProductIdChanging(value);
                ReportPropertyChanging("ProductId");
                _ProductId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ProductId");
                OnProductIdChanged();
            }
        }
        private global::System.Int32 _ProductId;
        partial void OnProductIdChanging(global::System.Int32 value);
        partial void OnProductIdChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ECommerceModel", "Product_Promotions", "Products")]
        public Product Product
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Product>("ECommerceModel.Product_Promotions", "Products").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Product>("ECommerceModel.Product_Promotions", "Products").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Product> ProductReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Product>("ECommerceModel.Product_Promotions", "Products");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Product>("ECommerceModel.Product_Promotions", "Products", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
